# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'plife' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for plife

	pod 'SQLClient', '~> 0.1.3'

  target 'plifeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'plifeUITests' do
    # Pods for testing
  end

end
